### ISSUE TITLE
No such file or directory: 'C\\dict.txt'

### ISSUE THREAD

**Issue by Alkabann** [pytorch/fairseq#1370]
When I try:

import torch
camembert = torch.hub.load('pytorch/fairseq', 'camembert.v0')
I have this error message:
No such file or directory: 'C\\dict.txt'

I have seen another post which seems to raise the same issue:
C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\masked_lm.py
in setup_task():
I CHANGED
paths = args.data.split(':') 
TO
paths = [args.data]

but iI have exactly the same error after this...

  File "<ipython-input-7-96fab3386019>", line 1, in <module>
    camembert = torch.hub.load('pytorch/fairseq', 'camembert.v0')

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\hub.py", line 359, in load
    model = entry(*args, **kwargs)

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\models\roberta\model.py", line 239, in from_pretrained
    **kwargs,

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 54, in from_pretrained
    arg_overrides=kwargs,

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\checkpoint_utils.py", line 182, in load_model_ensemble_and_task
    task = tasks.setup_task(args)

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\masked_lm.py", line 69, in setup_task
    dictionary = Dictionary.load(os.path.join(paths[0], 'dict.txt'))

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 188, in load
    d.add_from_file(f, ignore_utf_errors)

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 205, in add_from_file
    raise fnfe

  File "C:\Users\aymer/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 199, in add_from_file
    with open(f, 'r', encoding='utf-8') as fd:

FileNotFoundError: [Errno 2] No such file or directory: 'C\\dict.txt'

**Comment by Korge** [comment]
Hi Alkabann,

I encounter the same error under W10. I'll tell you if I find a solution (you're not alone !)

**Comment by Korge** [comment]
Hi again ! Surprisingly I found the problem !

It seems that the behavior of the script "masked_lm" (in fairseq/fairseq/tasks) is wrong in this case.

In the function setup_task (line 69) the dictionnary is load by :
dictionary = Dictionary.load(os.path.join(paths[0], 'dict.txt'))

However in our case, paths is ['C', '\\Users\\USERNAME\\Desktop\\camemBERT\\camembert.v0']

Then, C/dict.txt doesn't exist. I fixed it (however that's not a real fix)

![image](https://user-images.githubusercontent.com/22307761/69064629-c2b28f00-0a1e-11ea-979e-85a3af43cb53.png)

**Comment by xsway** [comment]
I ran into the same problem. This should be marked as bug.

**Comment by huihuifan** [comment]
@louismartin  can you take a look at this?

**Comment by myleott** [comment]
Fixed by cd521b4a7c7334c5bac08063bdf73768a7a70c9f

**Comment by AyoubAjarra** [comment]
Hi everyone, It's been a week now that I'm trying to solve this problem, and I'm still stuck with the same error, I tried the solution suggested by @myleott but still receive the same error ,  I hope we can solve this problem as soon as possible

**Comment by myleott** [comment]
Can you try again with `force_reload=True`? Something like
```
camembert = torch.hub.load('pytorch/fairseq', 'camembert.v0', force_reload=True)
```

**Comment by lg0killer** [comment]
I had to rebuild locally as the one on pip is does not contain the changes

Just run:
- python -m pip uninstall fairseq
- git clone https://github.com/pytorch/fairseq.git
- cd fairseq
- python setup.py install

Hope this helps

**Comment by ericbrunetgouet** [comment]
Dear Ig0killer,
Thanks a lot. I was just facing that same bug, this morning (on a PC - btw I had this issue on my macbook) and your solution did work. I just uninstalled fairseq and downloaded the fairseq git directory, then used python setup.py install.
Best wishes to everybody for 2020,
Eric Brunet-Gouet

**Comment by ryonakamura** [comment]
Perhaps fairseq-eval-lm only supports language models?
I want to get ppl with MT transformer in my corpus but I get similar error.

**Comment by Worien** [comment]
Faced with the similar issue on linux:
```
Traceback (most recent call last):
  File "/home/pavel.pugach/.pyenv/versions/3.7.9/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/pavel.pugach/fairseq/fairseq_cli/train.py", line 477, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/pavel.pugach/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/home/pavel.pugach/fairseq/fairseq_cli/train.py", line 82, in main
    task = tasks.setup_task(cfg.task)
  File "/home/pavel.pugach/fairseq/fairseq/tasks/__init__.py", line 44, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/pavel.pugach/fairseq/fairseq/tasks/sentence_prediction.py", line 118, in setup_task
    source=True,
  File "/home/pavel.pugach/fairseq/fairseq/tasks/sentence_prediction.py", line 106, in load_dictionary
    dictionary = Dictionary.load(filename)
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 215, in load
    d.add_from_file(f)
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 228, in add_from_file
    raise fnfe
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 225, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'RTE-bin/input0/dict.txt'
```
Can't run training for rxf
